# Generated by Django 4.2.23 on 2025-08-26 12:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Excluído em"
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome do Cargo"
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição detalhada das responsabilidades do cargo",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "salario_base",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Salário base para este cargo",
                        max_digits=10,
                        null=True,
                        verbose_name="Salário Base",
                    ),
                ),
                (
                    "nivel_hierarquico",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="1 = Mais alto, números maiores = níveis mais baixos",
                        verbose_name="Nível Hierárquico",
                    ),
                ),
                (
                    "cor_identificacao",
                    models.CharField(
                        default="#007bff",
                        help_text="Cor hexadecimal para identificação visual",
                        max_length=7,
                        verbose_name="Cor de Identificação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cargo",
                "verbose_name_plural": "Cargos",
                "ordering": ["nivel_hierarquico", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Excluído em"
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome Completo"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "telefone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Número de telefone deve estar no formato: '+999999999'. Até 15 dígitos permitidos.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Telefone",
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Número de WhatsApp deve estar no formato: '+999999999'. Até 15 dígitos permitidos.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="WhatsApp",
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        max_length=14,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="CPF deve estar no formato: 000.000.000-00",
                                regex="^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$",
                            )
                        ],
                        verbose_name="CPF",
                    ),
                ),
                ("rg", models.CharField(blank=True, max_length=20, verbose_name="RG")),
                (
                    "data_nascimento",
                    models.DateField(verbose_name="Data de Nascimento"),
                ),
                ("endereco", models.CharField(max_length=200, verbose_name="Endereço")),
                ("cidade", models.CharField(max_length=100, verbose_name="Cidade")),
                ("estado", models.CharField(max_length=2, verbose_name="Estado")),
                (
                    "cep",
                    models.CharField(
                        max_length=9,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="CEP deve estar no formato: 00000-000",
                                regex="^\\d{5}-\\d{3}$",
                            )
                        ],
                        verbose_name="CEP",
                    ),
                ),
                (
                    "matricula",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Matrícula"
                    ),
                ),
                ("data_admissao", models.DateField(verbose_name="Data de Admissão")),
                (
                    "data_demissao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Demissão"
                    ),
                ),
                (
                    "salario_atual",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Salário Atual"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("inativo", "Inativo"),
                            ("ferias", "Férias"),
                            ("licenca", "Licença"),
                            ("demitido", "Demitido"),
                        ],
                        default="ativo",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "turno",
                    models.CharField(
                        choices=[
                            ("manha", "Manhã"),
                            ("tarde", "Tarde"),
                            ("noite", "Noite"),
                            ("integral", "Integral"),
                            ("plantao", "Plantão"),
                        ],
                        default="integral",
                        max_length=20,
                        verbose_name="Turno de Trabalho",
                    ),
                ),
                (
                    "horario_entrada",
                    models.TimeField(verbose_name="Horário de Entrada"),
                ),
                ("horario_saida", models.TimeField(verbose_name="Horário de Saída")),
                (
                    "dias_trabalho",
                    models.CharField(
                        default="seg-sex",
                        help_text="Ex: seg-sex, seg-sab, etc.",
                        max_length=20,
                        verbose_name="Dias de Trabalho",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="funcionarios/fotos/",
                        verbose_name="Foto",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "especialidades",
                    models.TextField(
                        blank=True,
                        help_text="Especialidades ou habilidades específicas",
                        verbose_name="Especialidades",
                    ),
                ),
                (
                    "contato_emergencia_nome",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Nome do Contato de Emergência",
                    ),
                ),
                (
                    "contato_emergencia_telefone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Telefone do Contato de Emergência",
                    ),
                ),
                (
                    "contato_emergencia_parentesco",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Parentesco do Contato de Emergência",
                    ),
                ),
            ],
            options={
                "verbose_name": "Funcionário",
                "verbose_name_plural": "Funcionários",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="HistoricoSalario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Excluído em"
                    ),
                ),
                (
                    "salario_anterior",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Salário Anterior"
                    ),
                ),
                (
                    "salario_novo",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Salário Novo"
                    ),
                ),
                ("data_alteracao", models.DateField(verbose_name="Data da Alteração")),
                (
                    "motivo",
                    models.TextField(blank=True, verbose_name="Motivo da Alteração"),
                ),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_salarios",
                        to="funcionarios.funcionario",
                        verbose_name="Funcionário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Salário",
                "verbose_name_plural": "Históricos de Salário",
                "ordering": ["-data_alteracao"],
            },
        ),
    ]
