# Generated by Django 4.2.23 on 2025-08-26 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("funcionarios", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicosalario",
            name="usuario_responsavel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário Responsável",
            ),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="cargo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="funcionarios",
                to="funcionarios.cargo",
                verbose_name="Cargo",
            ),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="usuario",
            field=models.OneToOneField(
                blank=True,
                help_text="Vinculação com usuário do sistema (opcional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="funcionario",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário do Sistema",
            ),
        ),
        migrations.AddIndex(
            model_name="funcionario",
            index=models.Index(fields=["status"], name="funcionario_status_d8c1d5_idx"),
        ),
        migrations.AddIndex(
            model_name="funcionario",
            index=models.Index(fields=["cargo"], name="funcionario_cargo_i_091a1d_idx"),
        ),
        migrations.AddIndex(
            model_name="funcionario",
            index=models.Index(
                fields=["matricula"], name="funcionario_matricu_53afb0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="funcionario",
            index=models.Index(fields=["cpf"], name="funcionario_cpf_dc5eae_idx"),
        ),
    ]
