# Generated by Django 4.2.23 on 2025-08-26 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicocontato",
            name="usuario_responsavel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário Responsável",
            ),
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(fields=["status"], name="clientes_cl_status_b31356_idx"),
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(
                fields=["tipo_cliente"], name="clientes_cl_tipo_cl_cae2d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(fields=["cpf"], name="clientes_cl_cpf_e6905f_idx"),
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(fields=["cnpj"], name="clientes_cl_cnpj_db43af_idx"),
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(
                fields=["telefone"], name="clientes_cl_telefon_08ef14_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(fields=["email"], name="clientes_cl_email_eae461_idx"),
        ),
    ]
