# Generated by Django 4.2.23 on 2025-08-26 12:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Excluído em"
                    ),
                ),
                (
                    "data_hora",
                    models.DateTimeField(verbose_name="Data e Hora do Agendamento"),
                ),
                (
                    "data_hora_fim",
                    models.DateTimeField(
                        blank=True,
                        help_text="Calculado automaticamente baseado na duração do serviço",
                        null=True,
                        verbose_name="Data e Hora de Término",
                    ),
                ),
                (
                    "duracao_prevista",
                    models.PositiveIntegerField(
                        help_text="Duração prevista em minutos (copiada do serviço)",
                        verbose_name="Duração Prevista (minutos)",
                    ),
                ),
                (
                    "duracao_real",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Duração real do atendimento",
                        null=True,
                        verbose_name="Duração Real (minutos)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("agendado", "Agendado"),
                            ("confirmado", "Confirmado"),
                            ("em_andamento", "Em Andamento"),
                            ("concluido", "Concluído"),
                            ("cancelado", "Cancelado"),
                            ("nao_compareceu", "Não Compareceu"),
                            ("reagendado", "Reagendado"),
                        ],
                        default="agendado",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_confirmacao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Confirmação"
                    ),
                ),
                (
                    "data_inicio_atendimento",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Data de Início do Atendimento",
                    ),
                ),
                (
                    "data_fim_atendimento",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Fim do Atendimento"
                    ),
                ),
                (
                    "data_cancelamento",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Cancelamento"
                    ),
                ),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("presencial", "Presencial"),
                            ("telefone", "Telefone"),
                            ("whatsapp", "WhatsApp"),
                            ("online", "Site/App"),
                            ("indicacao", "Indicação"),
                        ],
                        default="presencial",
                        max_length=20,
                        verbose_name="Origem do Agendamento",
                    ),
                ),
                (
                    "valor_servico",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor cobrado pelo serviço (copiado do serviço no momento do agendamento)",
                        max_digits=10,
                        verbose_name="Valor do Serviço",
                    ),
                ),
                (
                    "desconto_aplicado",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Desconto Aplicado",
                    ),
                ),
                (
                    "valor_final",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor final após aplicação de descontos",
                        max_digits=10,
                        verbose_name="Valor Final",
                    ),
                ),
                (
                    "forma_pagamento",
                    models.CharField(
                        choices=[
                            ("dinheiro", "Dinheiro"),
                            ("cartao_credito", "Cartão de Crédito"),
                            ("cartao_debito", "Cartão de Débito"),
                            ("pix", "PIX"),
                            ("transferencia", "Transferência"),
                            ("boleto", "Boleto"),
                            ("nao_definido", "Não Definido"),
                        ],
                        default="nao_definido",
                        max_length=20,
                        verbose_name="Forma de Pagamento",
                    ),
                ),
                (
                    "pago",
                    models.BooleanField(
                        default=False, verbose_name="Pagamento Realizado"
                    ),
                ),
                (
                    "data_pagamento",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data do Pagamento"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True,
                        help_text="Observações gerais sobre o agendamento",
                        verbose_name="Observações",
                    ),
                ),
                (
                    "observacoes_cliente",
                    models.TextField(
                        blank=True,
                        help_text="Observações ou solicitações específicas do cliente",
                        verbose_name="Observações do Cliente",
                    ),
                ),
                (
                    "observacoes_funcionario",
                    models.TextField(
                        blank=True,
                        help_text="Observações do funcionário sobre o atendimento",
                        verbose_name="Observações do Funcionário",
                    ),
                ),
                (
                    "motivo_cancelamento",
                    models.TextField(blank=True, verbose_name="Motivo do Cancelamento"),
                ),
                (
                    "avaliacao",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Avaliação do cliente sobre o serviço",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Avaliação (1-5)",
                    ),
                ),
                (
                    "comentario_avaliacao",
                    models.TextField(
                        blank=True, verbose_name="Comentário da Avaliação"
                    ),
                ),
                (
                    "data_avaliacao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data da Avaliação"
                    ),
                ),
                (
                    "lembrete_enviado",
                    models.BooleanField(
                        default=False,
                        help_text="Se o lembrete foi enviado ao cliente",
                        verbose_name="Lembrete Enviado",
                    ),
                ),
                (
                    "data_lembrete",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data do Lembrete"
                    ),
                ),
                (
                    "confirmacao_enviada",
                    models.BooleanField(
                        default=False,
                        help_text="Se a confirmação foi enviada ao cliente",
                        verbose_name="Confirmação Enviada",
                    ),
                ),
                (
                    "numero_reagendamentos",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Número de Reagendamentos"
                    ),
                ),
            ],
            options={
                "verbose_name": "Agendamento",
                "verbose_name_plural": "Agendamentos",
                "ordering": ["-data_hora"],
            },
        ),
        migrations.CreateModel(
            name="Notificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Excluído em"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("lembrete", "Lembrete"),
                            ("confirmacao", "Confirmação"),
                            ("cancelamento", "Cancelamento"),
                            ("reagendamento", "Reagendamento"),
                            ("avaliacao", "Solicitação de Avaliação"),
                            ("promocao", "Promoção"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Notificação",
                    ),
                ),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("sms", "SMS"),
                            ("email", "Email"),
                            ("push", "Push Notification"),
                        ],
                        max_length=20,
                        verbose_name="Canal de Envio",
                    ),
                ),
                (
                    "destinatario",
                    models.CharField(
                        help_text="Número de telefone, email, etc.",
                        max_length=100,
                        verbose_name="Destinatário",
                    ),
                ),
                ("assunto", models.CharField(max_length=200, verbose_name="Assunto")),
                ("mensagem", models.TextField(verbose_name="Mensagem")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("enviada", "Enviada"),
                            ("entregue", "Entregue"),
                            ("lida", "Lida"),
                            ("erro", "Erro"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_agendamento",
                    models.DateTimeField(verbose_name="Data de Agendamento do Envio"),
                ),
                (
                    "data_envio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Envio"
                    ),
                ),
                (
                    "data_entrega",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Entrega"
                    ),
                ),
                (
                    "data_leitura",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Leitura"
                    ),
                ),
                (
                    "erro_detalhes",
                    models.TextField(blank=True, verbose_name="Detalhes do Erro"),
                ),
                (
                    "tentativas",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tentativas de Envio"
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificação",
                "verbose_name_plural": "Notificações",
                "ordering": ["-data_agendamento"],
            },
        ),
        migrations.CreateModel(
            name="StatusAgendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Excluído em"
                    ),
                ),
                (
                    "status_anterior",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("agendado", "Agendado"),
                            ("confirmado", "Confirmado"),
                            ("em_andamento", "Em Andamento"),
                            ("concluido", "Concluído"),
                            ("cancelado", "Cancelado"),
                            ("nao_compareceu", "Não Compareceu"),
                            ("reagendado", "Reagendado"),
                        ],
                        max_length=20,
                        verbose_name="Status Anterior",
                    ),
                ),
                (
                    "status_novo",
                    models.CharField(
                        choices=[
                            ("agendado", "Agendado"),
                            ("confirmado", "Confirmado"),
                            ("em_andamento", "Em Andamento"),
                            ("concluido", "Concluído"),
                            ("cancelado", "Cancelado"),
                            ("nao_compareceu", "Não Compareceu"),
                            ("reagendado", "Reagendado"),
                        ],
                        max_length=20,
                        verbose_name="Status Novo",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True, verbose_name="Observações sobre a Mudança"
                    ),
                ),
                (
                    "data_mudanca",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Mudança"
                    ),
                ),
                (
                    "agendamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_status",
                        to="agendamentos.agendamento",
                        verbose_name="Agendamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Status",
                "verbose_name_plural": "Históricos de Status",
                "ordering": ["-data_mudanca"],
            },
        ),
    ]
