# Generated by Django 4.2.23 on 2025-08-26 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agendamentos", "0001_initial"),
        ("servicos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("funcionarios", "0001_initial"),
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="statusagendamento",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário Responsável",
            ),
        ),
        migrations.AddField(
            model_name="notificacao",
            name="agendamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notificacoes",
                to="agendamentos.agendamento",
                verbose_name="Agendamento",
            ),
        ),
        migrations.AddField(
            model_name="notificacao",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notificacoes",
                to="clientes.cliente",
                verbose_name="Cliente",
            ),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="agendamento_original",
            field=models.ForeignKey(
                blank=True,
                help_text="Referência ao agendamento original em caso de reagendamento",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reagendamentos",
                to="agendamentos.agendamento",
                verbose_name="Agendamento Original",
            ),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="agendamentos",
                to="clientes.cliente",
                verbose_name="Cliente",
            ),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="funcionario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="agendamentos",
                to="funcionarios.funcionario",
                verbose_name="Funcionário",
            ),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="pacote",
            field=models.ForeignKey(
                blank=True,
                help_text="Se este agendamento faz parte de um pacote",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agendamentos",
                to="servicos.pacoteservico",
                verbose_name="Pacote de Serviços",
            ),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="servico",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="agendamentos",
                to="servicos.servico",
                verbose_name="Serviço",
            ),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="usuario_agendou",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agendamentos_criados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário que Agendou",
            ),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="usuario_cancelou",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agendamentos_cancelados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário que Cancelou",
            ),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="usuario_confirmou",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agendamentos_confirmados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário que Confirmou",
            ),
        ),
        migrations.AddIndex(
            model_name="agendamento",
            index=models.Index(
                fields=["data_hora"], name="agendamento_data_ho_8f71cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agendamento",
            index=models.Index(fields=["status"], name="agendamento_status_24d1a6_idx"),
        ),
        migrations.AddIndex(
            model_name="agendamento",
            index=models.Index(
                fields=["cliente"], name="agendamento_cliente_f6874f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agendamento",
            index=models.Index(
                fields=["funcionario"], name="agendamento_funcion_55a35e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agendamento",
            index=models.Index(
                fields=["servico"], name="agendamento_servico_bdf63b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agendamento",
            index=models.Index(
                fields=["data_hora", "status"], name="agendamento_data_ho_fb44eb_idx"
            ),
        ),
    ]
